In [1]:
from rank_bm25 import BM25Okapi
from BM25_3 import BM25
# import numpy as np
# import pandas as pd

In [2]:
docs = {
	    "D1": list("abcbd"),
	    "D2": list("befb"),
	    "D3": list("bgcd"),
	    "D4": list("bde"),
	    "D5": list("abeg"),
	    "D6": list("bghh")
}
    
query = {"Q1": list("aaacch")}

# Their BM25

In [3]:
bm25 = BM25Okapi(docs.values(), k1=1.2, b=0.75, epsilon=1)

self.corpus_size = 6
word = a, freq = 2, idf = 0.5877866649021191
word = b, freq = 6, idf = -2.5649493574615367
word = c, freq = 2, idf = 0.5877866649021191
word = d, freq = 3, idf = 0.0
word = e, freq = 3, idf = 0.0
word = f, freq = 1, idf = 1.2992829841302609
word = g, freq = 3, idf = 0.0
word = h, freq = 1, idf = 1.2992829841302609


In [4]:
doc_scores = bm25.get_scores(query["Q1"])
doc_scores

self.doc_freqs = [{'a': 1, 'b': 2, 'c': 1, 'd': 1}, {'b': 2, 'e': 1, 'f': 1}, {'b': 1, 'g': 1, 'c': 1, 'd': 1}, {'b': 1, 'd': 1, 'e': 1}, {'a': 1, 'b': 1, 'e': 1, 'g': 1}, {'b': 1, 'g': 1, 'h': 2}]
self.idf = {'a': 0.5877866649021191, 'b': -2.5649493574615367, 'c': 0.5877866649021191, 'd': 0.0, 'e': 0.0, 'f': 1.2992829841302609, 'g': 0.0, 'h': 1.2992829841302609}
q = a
q_freq = [1 0 0 0 1 0]
q = a
q_freq = [1 0 0 0 1 0]
q = a
q_freq = [1 0 0 0 1 0]
q = c
q_freq = [1 0 1 0 0 0]
q = c
q_freq = [1 0 1 0 0 0]
q = h
q_freq = [0 0 0 0 0 2]


array([2.66624879, 0.        , 1.17557333, 0.        , 1.76335999,
       1.7865141 ])

# My BM25

In [5]:
bm25 = BM25(docs, query, load=False)

Previous file not found...
Catching vectorised fis and qfis for faster calculations (takes ~2 mins)
Starting docs... done
    dl  h  a  c
D1   5  0  1  1
D2   4  0  0  0
D3   4  0  0  1
D4   3  0  0  0
D5   4  0  1  0
D6   4  2  0  0
Starting queries... done
    a  c  h
Q1  3  2  1
self.Is =
 ['h', 'a', 'c']
self.D =
     dl  h  a  c
D1   5  0  1  1
D2   4  0  0  0
D3   4  0  0  1
D4   3  0  0  0
D5   4  0  1  0
D6   4  2  0  0
self.Q =
     h  a  c
Q1  1  3  2


In [6]:
doc_scores = bm25.get_scores()
doc_scores

doc_part:
[[0.         0.96385542 0.96385542]
 [0.         0.         0.        ]
 [0.         0.         1.        ]
 [0.         0.         0.        ]
 [0.         1.         0.        ]
 [1.11111111 0.         0.        ]]

k =  [[1 2 2]]
idf =
[[1.29928298 0.58778666 0.58778666]
 [1.29928298 0.58778666 0.58778666]
 [1.29928298 0.58778666 0.58778666]
 [1.29928298 0.58778666 0.58778666]
 [1.29928298 0.58778666 0.58778666]
 [1.29928298 0.58778666 0.58778666]]

query_part:
[[1.         1.57142857 1.375     ]]



array([[1.66927366, 0.        , 0.80820666, 0.        , 0.92366476,
        1.44364776]])