In [70]:
import numpy as np
import pandas as pd

In [71]:
cache = "cache/"
nameEnd = "2914_50.csv"

In [81]:
D = pd.read_csv(cache + "d_" + nameEnd)
Q = pd.read_csv(cache + "q_" + nameEnd)

In [112]:
print(len(dl), len(Is))
k = np.zeros((len(dl), len(Is)))

2914 2057


In [113]:
for i in range(len(Is)): k[:, i] = dl

In [115]:
k.shape

(2914, 2057)

In [108]:
N = 3
a = np.random.rand(N,N)
print("a =", a, "\n")
b = np.zeros((N,N+1))
print("b =", b, "\n")
b[:,:-1] = a
print("b =", b, "\n")

a = [[0.6774426  0.62723787 0.44866844]
 [0.84219688 0.14972848 0.10320153]
 [0.60101695 0.85176582 0.36312894]] 

b = [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

b = [[0.6774426  0.62723787 0.44866844 0.        ]
 [0.84219688 0.14972848 0.10320153 0.        ]
 [0.60101695 0.85176582 0.36312894 0.        ]] 



In [93]:
x = np.array([[1],
              [2],
              [3]])

In [104]:
y = x.reshape((3,5))

ValueError: cannot reshape array of size 3 into shape (3,5)

In [103]:
y

array([[ 5],
       [10],
       [15]])

In [145]:
a = np.array([[1, 2, 3], [2, 3, 4]])
b = a*2

In [148]:
a

array([[1, 2, 3],
       [2, 3, 4]])

In [73]:
D

Unnamed: 0    dl  pw9  premis  concern  extract  sharp  alibi  household  \
0            C1   702    0       0        3        0      0      0          0   
1           C10  4197    0      16        9        0      0      0          0   
2          C100  2561    0       0        1        0      0      0          0   
3         C1000  1242    0       1        0        0      1      0          0   
4         C1001   189    0       0        0        0      0      0          0   
...         ...   ...  ...     ...      ...      ...    ...    ...        ...   
2909       C995  1797    0       0        0        0      0      0          0   
2910       C996  1189    0       0        3        0      0      0          0   
2911       C997   636    0       0        0        0      0      0          0   
2912       C998  2179    0       0        1        2      0      0          0   
2913       C999   879    0       0        0        0      0      0          0   

      paper  ...  rush  follow  companion  affirm  feel  sketch  user  katta  \
0         0  ...     0       1          0       0     0       0     0      0   
1         0  ...     0       4          0       0     1       0     0      0   
2         0  ...     0       2          0       2     0       0     0      0   
3         0  ...     0       1          0       0     0       3     0      0   
4         0  ...     0       3          0       0     0       0     0      0   
...     ...  ...   ...     ...        ...     ...   ...     ...   ...    ...   
2909      0  ...     0       3          0       0     0       0     0      0   
2910      0  ...     0       1          0       0     0       0     0      0   
2911      0  ...     0       1          0       0     0       0     0      0   
2912      1  ...     0       5          0       2     1       0     0      0   
2913      0  ...     0       3          0       0     0       0     0      0   

      unless  hit  
0          1    0  
1          3    0  
2          4    0  
3          1    0  
4          0    0  
...      ...  ...  
2909       0    0  
2910       1    0  
2911       0    0  
2912       4    0  
2913       1    0  

[2914 rows x 2059 columns]

In [78]:
Is = D.columns.tolist()[2:]
print(Is[:10], "...")
print(f"len = {len(Is)}")

['pw9', 'premis', 'concern', 'extract', 'sharp', 'alibi', 'household', 'paper', 'seriou', 'livelihood'] ...
len = 2057


In [137]:
fi = D.loc[:, Is[0]:].to_numpy(dtype=np.int32)
k1 = 0.25
k2 = 1.2
b = 0.75

In [ ]:
dp = (k1+1)*fi/(fi+k1*(1-b+b*dl/1694))
dp

In [59]:
fi.sum(axis = 1).shape

(2914,)

In [52]:
dp.shape

(2914, 2057)

In [62]:
len(D.loc[D["classmat"] != 0])

3

In [197]:
k = np.array(D.loc[:, "dl"]).reshape((len(D), 1))
# print(k.shape)
o = np.ones((1, len(Is)))
# o.shape
dl = np.dot(k, o)

In [195]:
dl.shape

(2914, 2057)

In [143]:
dp = ((k1+1)*fi)/(fi+k1*(1-b+b*dl/1694))
dp.shape

(2914, 2057)

In [134]:
dp

array([[0.        , 0.        , 1.19419118, ..., 0.        , 1.09629821,
        0.        ],
       [0.        , 1.21013776, 1.18084896, ..., 0.        , 1.06321328,
        0.        ],
       [0.        , 0.        , 0.92870261, ..., 0.        , 1.15049281,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.9588227 , ..., 0.        , 1.16179585,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.07777955,
        0.        ]])

In [175]:
ni = np.count_nonzero(dp, axis = 0).reshape((2057, 1))
ni

array([[  70],
       [ 438],
       [1857],
       ...,
       [  14],
       [1061],
       [ 373]], dtype=int64)

In [177]:
x = np.array([[1],
              [2],
              [3]])
o = np.ones((1, 4))

np.dot(x, o)

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [203]:
np.count_nonzero(fi, axis = 0).reshape((1, len(Is)))

(1, 2057)

In [207]:
x.T

array([[1, 2, 3]])